# Generated by Django 4.0.4 on 2022-04-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loginID', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('total_room', models.IntegerField()),
                ('total_device', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_device', models.IntegerField()),
                ('total_in', models.IntegerField()),
                ('total_out', models.IntegerField()),
                ('present_in', models.IntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mac_id', models.CharField(max_length=100)),
                ('post_url', models.CharField(max_length=300)),
                ('get_url', models.CharField(max_length=300)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
