# Generated by Django 4.0.4 on 2022-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='authtoken',
            field=models.CharField(default='kkokok', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='total_device',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='total_room',
            field=models.IntegerField(default=0),
        ),
    ]
