# Generated by Django 4.0.4 on 2022-04-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_device_mac_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='limit',
            field=models.IntegerField(default=1),
        ),
    ]
